### ISSUE TITLE
Weird radar point cloud

### ISSUE THREAD

**Issue by shawrby** [kaist-avelab/K-Radar#1]
Thank you for your great research.

I processed the radar cube with CFAR and extracted the radar point cloud as shown in the figure below.

![image](https://user-images.githubusercontent.com/54407464/213061254-7f80a0bd-5609-43cc-a27f-0251654c2e04.png)

Is this radar point cloud correct?

**Comment by DongHeePaek** [comment]
Hello, @shawrby

We appreciate for you for your interest for our work.

The hyper-parameters for CFAR has not been optimized, since we utilize 'quantile' function for the network input.

We recommend you to adjust the hyper-parameters for CFAR by comparing the Radar point cloud with the calibrated Lidar point cloud.

The function is on line 673 of https://github.com/kaist-avelab/K-Radar/blob/f561bb5373e6d5aa85309310553ff2d63440c506/datasets/kradar_detection_v1_0.py

In addition, the hyper-parameters for CFAR are on line 130 of https://github.com/kaist-avelab/K-Radar/blob/main/configs/cfg_RTNH.yml.

Thank you.

**Comment by yangxh11** [comment]
The size is too large. Would consider split the lidar point cloud files separately?

**Comment by Toytiny** [comment]
Hi, @shawrby, we are also trying to generate decent point clouds from radar tensor. Have you got any ideal results after adjusting hyper-parameters for CFAR?

**Comment by DongHeePaek** [comment]
For the latest updates for 4D Radar point cloud, please refer to following two materials:
1. 'Example of 4D Radar point cloud data' section & 2. vis_in_open3d function in 'kradar_detection_v2_0.py'.
