### ISSUE TITLE
The data in NAS is too large.

### ISSUE THREAD

**Issue by YLRK** [kaist-avelab/K-Radar#11]
Thank you for your great research.

The data in NAS is too large and the download speed is too slow, making it easy to interrupt the download. Can you decompress the data in NAS into small compressed packets?
![image](https://user-images.githubusercontent.com/55654587/228401430-19916834-bd1c-4462-a964-1a32f30930ed.png)

**Comment by kvnptl** [comment]
True, the download speed is just 50KB/s

**Comment by DekuLiuTesla** [comment]
Yeah, mine is 200-300KB/s but is still too slow for downloading 12T. The sequences from 21-58 on Google Drive seem to contain no RT data. Is there any recommended practice for relatively faster downloading?

**Comment by LiawWun** [comment]
Have you succeeded in downloading the dataset from their NAS server? Since i'm facing the same issue now.

**Comment by woo9904** [comment]
Hello everyone. 

I'll reply on their behalf.

First of all, I would like to apologize for the difficulties you've encountered in obtaining the dataset.

Should you require the complete dataset, including the full Tensor data, we suggest a different acquisition method.
That is sending the hard disk directly.

We kindly request that you provide us with an external hard disk drive (HDD) with a capacity of 18TB or greater. You can send it through international shipping or purchase it via online platforms like Amazon. This data transfer is strictly non-profit basis and has been utilized by various research institutions and corporations.

If you are interested in receiving the full dataset directly on an external HDD, please send an email to @DongHeePaek or me.

Thank you.

**Comment by DongHeePaek** [comment]
I am writing to clarify a point that **the complete dataset was accessible before the camera-ready deadline**. We initially shared it via a local server, acknowledging the slower download speeds from this source. To mitigate this, we offered two alternatives:

Firstly, the dataset has been made available through **shipping**, a method documented on our GitHub page in the "Sending 4D raw data via shipping" section. **This approach has been successfully adopted by various institutions and companies**.

Secondly, a **partial dataset was shared via Google Drive**. Due to its 2TB storage limit and the dataset's size of 16TB, including processed data like the Radar cube, full sharing on this platform was impractical. The associated costs, 119,000 KRW per year for 2TB, meant a total annual cost of 952,000 KRW for 16TB, **necessitating eight members to forego personal drive usage and share costs**. These constraints led us to recommend the local server or shipping method for full dataset access.

We deeply regret the inconvenience caused by the size of the K-Radar dataset and are committed to providing the best possible support for all shipping inquiries received via email. Should you require the full dataset, please do not hesitate to contact us as mentioned in the "Sending 4D raw data via shipping" section of our GitHub page.

**Comment by VRehnberg** [comment]
The slow download speed from the NAS is probably due to the download going through Synology's internet service which rate limits the downloads.

Quick Connect could maybe be an option but that has security implications. Other options would be to set up something else on the same network that could be used for port forwarding or some sftp or scp. I do think considering alternatives to physically shipping disks would ease of access a lot.
