### ISSUE TITLE
Total dataset size?

### ISSUE THREAD

**Issue by kvnptl** [kaist-avelab/K-Radar#3]
Hello,

As it's mentioned in the README file that dataset is too large. Could you please mention the total dataset size? So that we can make a proper storage arrangement at our end?

My guess is around ~13 TB (after checking server files)

Thanks,
K

**Comment by woo9904** [comment]
Hello @kvnptl 

I will respond on their behalf.

Excluding the post-processed data (e.g., cubes), it amounts to 13TB. If you include the post-processed data, it's approximately 16TB in total.

Additionally, due to the very large size of the data, receiving it on the local server may pose a problem with slow speeds. 
So, we kindly request that you provide us with an **external hard disk drive (HDD) with a capacity of 18TB or greater.** 
We are flexible regarding the method of provision; options include international shipping or procurement through online platforms such as Amazon.
I would like to emphasize that this data-sharing method operates on a **non-profit** basis and has been utilized by various research institutions and corporations.

If you are interested in receiving the full dataset directly on an external HDD, please send an email to @DongHeePaek or me.

Thank you.
